# Generated by Django 4.0.5 on 2022-06-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faith',
            old_name='descrption',
            new_name='description',
        ),
    ]
